name: build action

on:
  workflow_dispatch
  # push:
  #   tags:
  #   - v*

concurrency:
  group: build-action-${{ github.head_ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:$(date +%s)

#   publish:
#     name: Publish release
#     needs:
#     - build
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/download-artifact@v3
#       with:
#         name: artifacts
#         path: dist

#     - name: Push build artifacts to PyPI
#       uses: pypa/gh-action-pypi-publish@v1.6.4
#       with:
#         skip_existing: true
#         user: __token__
#         password: ${{ secrets.PYPI_TOKEN }}


